#!/usr/bin/env node

let argv = {_: process.argv.slice(2)}//require('minimist')(process.argv.slice(2))
let bitfiles = require('.')
let bitdb = require('./bitdb')

let action = argv._[0]
if (!action || action == '--help' || action == '-h') {
	let path = require('path')
	let readme = require('fs').readFileSync(path.join(path.dirname(module.filename), 'README.md'))
	process.stdout.write(readme)
	process.exit()
}
let url = argv._[1]
if (!url) { url = action; action = 'status' }
url = url.split('://')
let type, path, id, dkey
if (url[1]) {
	type = url[0].toUpperCase()
	path = url[1].split('/')
	id = path.shift()
	dkey = path.join('/')
} else {
	type = 'TX'
	path = url[0]
	id = url[0]
}

if (action == 'status') {
	if (type == 'TX') {
		bitfiles.txstatus(id).catch(x=>{console.log(x); process.exit(-1);})
	} else if (type == 'ADDR' || type == 'BITCOIN') {
		bitfiles.addrstatus(id)
	} else if (type == 'D') {
		if (dkey) {
			bitfiles.dstatus(id, dkey)
		} else {
			bitfiles.dlog(id)
		}
	} else if (type == 'BCAT') {
		bitfiles.bcatstatus(id)
	} else if (type == 'C') {
		bitfiles.cstatus(id)
	} else if (type == 'B') {
		bitfiles.bstatus(id)
	}
} else if (action == 'list') {
	if (dkey) {
		bitfiles.dstatus(id, dkey, 'list')
	} else {
		bitfiles.dlog(id, 'list')
	}
} else if (action == 'quickcheck') {
	(()=>{
		if (type == 'D') {
			return bitfiles.dstatus(id, dkey, 'quick')
		}
	})().catch(e=>{
		console.log(e)
		process.exit(-1)
	})
} else if (action == 'stream') {
	if (type == 'BCAT') {
		bitfiles.bcatstream(id, process.stdout)
	} else if (type == 'B') {
		bitfiles.bstream(id, process.stdout)
	} else if (type == 'D') {
		bitfiles.dstream(id, process.stdout, dkey)
	} else if (type == 'TX') {
		bitfiles.txstream(id, process.stdout)
	}
} else if (action == 'download') {
	if (type == 'D') {
		bitfiles.ddownload(id, dkey)
	} else if (type == 'BCAT') {
		bitfiles.bcatdownload(id)
	} else if (type == 'B') {
		bitfiles.bdownload(id)
	} else if (type == 'TX') {
		bitfiles.txdownload(id)
	} else if (type == 'ADDR' || type == 'BITCOIN') {
		bitfiles.addrdownload(id)
	}
} else if (action == 'bitdb') {
	(async () => {
		let r = await bitdb.bitdb(JSON.parse(argv._[1]))
		console.log(JSON.stringify(r))
	})()
}


